version: '3.9'
services:
  postgres_server:
    build: .
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  
  server:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://authenticator:pass@postgres_server:5432/postgres
      PGRST_DB_SCHEMA: ft
      PGRST_DB_ANON_ROLE: web_anon
      PGRST_SERVER_PROXY_URI: http://127.0.0.1:3000
    depends_on:
      - postgres_server
  
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    environment:
      API_URL: http://localhost:3000/
    
volumes:
  db_data: